# Build Docker image using https://drone.io/ CI/CD and publish it to https://hub.docker.com/r/citrinru/checkzone/
---
pipeline:
  docker:
    image: plugins/docker
    repo: citrinru/checkzone
    secrets: [ docker_username, docker_password ]
    tags: latest
    when:
      event: [push, tag]
